### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by simonwjackson** [mjs7231/python-plexapi#9] opened 2015-06-01 07:26 UTC
I'd like to incorporate some automated tests into the project, especially for the code submitted for #7 
In the past, i've used **py.test** but id be open to another framework if you are partial to one.

**Comment by mjs7231** [comment] 2015-06-01 13:08
I'm not partial to any framework. Right now I just have a few very basic tests in examples/tests.py. If that's not enough for you then maybe we do need to incorporate some kind of framework.

**Comment by mjs7231** [comment] 2017-01-26 06:50
I'm closing this one as a dupe of #92. Automated testing is coming very shortly, and the main discussion is in that bug.

**Closed by mjs7231** 2017-01-26 06:50 UTC
Labels: testing
